# Generated by Django 4.0.2 on 2022-04-18 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='pDesc',
            field=models.CharField(default=0.0002, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pClass',
            field=models.IntegerField(),
        ),
    ]
